### ISSUE TITLE
Create Hero Component

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/wds-react#1] opened 2023-10-26 19:52 UTC
The Page Intro, aka hero component needs to be added to our component library.

This component consists of other components that also need to be flushed out:

- [ ] Breadcrumbs
- [ ] Heading (h1)
- [ ] Title
- [ ] Caption
- [ ] Mission Status
- [ ] Metadata/Stats
- [ ] Background Image

Examples:

![image](https://github.com/NASA-PDS/wds-react/assets/931107/c675253a-eead-4e00-af56-e91e3ae5dc98)

![image](https://github.com/NASA-PDS/wds-react/assets/931107/b0497dff-662b-4d3f-bc26-8106457b2b4f)

![image](https://github.com/NASA-PDS/wds-react/assets/931107/e61abb9f-27a0-4157-a10e-1370829e1859)

![image](https://github.com/NASA-PDS/wds-react/assets/931107/1ca2ec2c-d060-454d-92a1-b8a4ba1188d4)

**Comment by jordanpadams** [comment] 2024-04-16 20:09
Duplicate of https://github.com/NASA-PDS/wds-react/issues/14

**Closed by jordanpadams** 2024-04-16 20:09 UTC
Labels: B14.1, B15.0, i&t.skip, sprint-backlog, task
